version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "Asia/Tokyo"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: nest-backend
    expose:
      - 3000
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/src:/app/src
      - ./backend/test:/app/test
      - ./backend/prisma:/app/prisma
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - app
    environment:
      NGINX_SERVER_NAME: ${NGINX_SERVER_NAME}
      NEST_HOST: ${NEST_HOST}
      NEST_PORT: 3000
      NGINX_MAX_BODY: ${NGINX_MAX_BODY}
      NGINX_PORT: ${NGINX_PORT}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}