FROM nginx:1.23.4-alpine

COPY ./entrypoint-nginx.sh /

RUN set -ex && \
	apk add --no-cache bash && \
	chmod +x /entrypoint-nginx.sh

COPY ./vhost.template /etc/nginx/conf.d/vhost.template
ADD ./cert-key/localhost.pem /etc/certs/localhost.pem
ADD ./cert-key/localhost-key.pem /etc/certs/localhost-key.pem

CMD ["/entrypoint-nginx.sh"]